apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding
spec:
  params:
  - name: gitrevision
    value: ""
  - name: gitrepositoryurl
    value: $(body.repository.url)