
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-cd
spec:
  workspaces:
    - name: source
    - name: ssh-creds
    - name: cluster-credentials
  params:
  - name: repo-url
    type: string
  - name: revision
    type: string
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.revision)
    workspaces:
      - name: output
        workspace: source
      - name: ssh-directory
        workspace: ssh-creds
  - name: list
    taskRef:
      name: list
    runAfter:
     - git-clone
    workspaces:
      - name: source
        workspace: source
  - name: deploy
    taskRef:
      name: deploy
    runAfter:
     - list
    workspaces:
      - name: source
        workspace: source
      - name: cluster-credentials
        workspace: cluster-credentials
      
      