apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: tekton
  name: list
spec:
  workspaces:
   - name: source
  steps:
    - name: echo
      image: alpine:3.18.3
      securityContext:
        runAsUser: 0
      # runAsNonRoot: true
      #   privileged: false
        allowPrivilegeEscalation: false
      #   capabilities:
      #     drop:
      #     - ALL
      #   seccompProfile:
      #     type: RuntimeDefault
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        ls
