apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-image
spec:
  workspaces:
  - name: source
  - name: dockerconfig
    mountPath: /root/.docker
  steps:
    - name: build-and-push
      image: quay.io/buildah/upstream:latest
      securityContext:
        runAsUser: 0
      # runAsNonRoot: true
        privileged: true
      # allowPrivilegeEscalation: false
      #   capabilities:
      #     drop:
      #     - ALL
      #   seccompProfile:
      #     type: RuntimeDefault
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        cd typescript
        buildah bud \
          --tag=ssoviedo/teste-tekton:1.3 \
          .
        
        buildah push ssoviedo/teste-tekton:1.3
