apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  workspaces:
  - name: source
  - name: cluster-credentials
    mountPath: /root/.kube
  steps:
    - name: deploy
      image: alpine
      securityContext:
        runAsUser: 0
      # runAsNonRoot: true
      #   privileged: false
        allowPrivilegeEscalation: false
      #   capabilities:
      #     drop:
      #     - ALL
      #   seccompProfile:
      #     type: RuntimeDefault
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        apk update
        apk add kubectl
        kubectl get pods
        kubectl apply -f teste-tekton/tekton.yaml